unit FPCConfigWriter;

{$mode ObjFPC}{$H+}

interface

uses
  Classes,
  Nova.Package, 
  SysUtils;

type
  TFPCConfigWriter = class
  public
    class procedure WriteConfig(NovaPkg: TNovaPackage;
      const FileName: string = FPC_FILE);
  end;

implementation

class procedure TFPCConfigWriter.WriteConfig(NovaPkg: TNovaPackage;
  const FileName: string);
var
  FPCLines: TStringList;

  procedure AddDepPaths(dep: TResolved);
  var
    PathVal: string;
    i: integer;
  begin
    // Construct vendor path
    PathVal := IncludeTrailingPathDelimiter(VENDOR_DIR) +
      StringReplace(dep.Name, '/', PathDelim, [rfReplaceAll]);

    PathVal := IncludeTrailingPathDelimiter(PathVal) + 'src';

    FPCLines.Add('-Fu ' + PathVal);
  end;

var
  i: integer;
  BaseConfig: string;
begin
  FPCLines := TStringList.Create;
  try
    // Determine base/system fpc.cfg
    {$IFDEF UNIX}
    BaseConfig := '/etc/fpc.cfg';
    {$ENDIF}
    {$IFDEF MSWINDOWS}
    BaseConfig := IncludeTrailingPathDelimiter(GetEnvironmentVariable('FPCDIR')) +
      'bin' + PathDelim + 'i386-win32' + PathDelim + 'fpc.cfg';
    {$ENDIF}

    // Add auto-generated header
    FPCLines.Add('#');
    FPCLines.Add('# Config file generated by nova on ' + DateToStr(Date) +
      ' - ' + TimeToStr(Time));
    FPCLines.Add('#');
    FPCLines.Add('');

    // Include base config if it exists
    if (BaseConfig <> '') and FileExists(BaseConfig) then
    begin
      FPCLines.Add('# Include system/base FPC configuration');
      FPCLines.Add('#include ' + BaseConfig);
      FPCLines.Add('');
    end;

    FPCLines.Add('# Vendor package search paths');

    // Add all top-level resolved packages
    for i := 0 to NovaPkg.ResolvedCount - 1 do
      AddDepPaths(NovaPkg.ResolvedAt(i));

    // Save the generated config
    FPCLines.SaveToFile(FileName);
    Writeln('Generated ', FileName);

  finally
    FPCLines.Free;
  end;
end;

end.
